sku_configs = {
        1: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[90, 50,50], "upper_bound":[130,255,255], "class_sku":4,"pixel_ratio" :0.4, "output_dir":"comfort_blue_cross_pack", "product_id":2}, #comfort _blue_860_ml_morning fresh
        2: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[0,50,50], "upper_bound":[10,255,255], "lower_bound_1": [160,50,50],"upper_bound_1":[180,255,255],"class_sku":4,"pixel_ratio" :0.4, "output_dir":"comfort_pink_cross_pack","product_id":2}, #comfort pink 860 ml lily fresh
        3: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[35, 50, 50], "upper_bound":[85, 255, 255], "class_sku":4,"pixel_ratio" :0.4, "output_dir":"comfort_green_cross_pack","product_id":2}, #comfort green 860 ml garden fresh 
        6: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[90, 50, 50], "upper_bound":[130, 255, 255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_matic_top_load_1ltr", "product_id":7}, #surf_excel_matic_top_load_1_ltr
        7: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[0,50,50], "upper_bound":[10, 255, 255],"lower_bound_1": [160, 50, 50],"upper_bound_1":[180,255,255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_matic_front_load_1_ltr", "product_id":7}, #surf_excel_matic_front_load_1_ltr
        8: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '>=',"lower_bound":[80, 50, 30], "upper_bound":[120, 255, 255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_Top_500_ml_cross_pack","product_id":20}, # surf execel matic top load 500 ml
        9: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '>=',"lower_bound":[110, 50, 50], "upper_bound":[150, 200, 255], "class_sku":1,"pixel_ratio" :0.1, "output_dir":"surf_excel_front_500_ml_cross_pack"}, #surf excel matic front load 500 ml
        10: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[0,0,180], "upper_bound":[180, 65, 255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_easy_wash_1ltr_cross_pack", "product_id":21}, #surf excel easy wash 1 ltr
        11: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '>=',"lower_bound":[0,0,180], "upper_bound":[180, 65, 255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_easy_wash_500_ml_cross_pack", "product_id":22}, #surf excel eash wash 500 ml 
        12: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[5, 100, 30], "upper_bound":[25, 255, 255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_quick_wash_1_ltr", "product_id":23}, #surf excel quick wash 1 ltr
        13: {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '>=',"lower_bound":[5, 100, 30], "upper_bound":[25, 255, 255], "class_sku":1,"pixel_ratio" :0.4, "output_dir":"surf_excel_quick_wash_500_ml", "product_id":24}, #surf excel quick wash 500 ml
        14:  {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[0,50, 50], "upper_bound":[10,255,255], "lower_bound_1": [160,50,50],"upper_bound_1":[180,255,255],"class_sku":0,"pixel_ratio" :0.4, "output_dir":"rin_front_load_cross_pack"}, #rin matic front load 1ltr
        15:  {"model_source": "serac2_cross_pack_07_03_2025.pt", "plc_ip": '192.168.20.124', "conf": 0.5, "y_axis":450, "y_condition": '<=',"lower_bound":[90, 50, 50], "upper_bound":[130, 255, 255], "class_sku":0,"pixel_ratio" :0.4, "output_dir":"rin_matic_top_load_cross_pack"}, #rin matic top load 1ltr
    }

ocr_configs = {
        1: { "ocr_light_tag":"TURNOFF_LIGHT","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":2, "ocr_count":29, "double_ocr_count":40}, #comfort _blue_860_ml_morning fresh
        2: {"ocr_light_tag":"TURNOFF_LIGHT","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":4, "ocr_count":29, "double_ocr_count":40}, #comfort pink 860 ml lily fresh
        3: {"ocr_light_tag":"TURNOFF_LIGHT","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":32, "ocr_count":29, "double_ocr_count":40}, #comfort green 860 ml garden fresh 
        4: {"ocr_light_tag":"TURNOFF_LIGHT","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":3, "ocr_count":29, "double_ocr_count":40}, #comfort black 860 ml desire
        5: {"ocr_light_tag":"TURNOFF_LIGHT","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":28, "ocr_count":29, "double_ocr_count":40}, #comfort black 860 ml royale
        6: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":30, "ocr_count":29, "double_ocr_count":40}, #rin matic front load 
        7: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":25, "ocr_count":29, "double_ocr_count":40}, #rin matic top load 
        8: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":31, "ocr_count":29, "double_ocr_count":40}, #surf excel matic front load 500 ml
        9: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":20, "ocr_count":29, "double_ocr_count":40}, # surf execel matic top load 500 ml
        10: {"ocr_light_tag":"TURNOFF_LIGHT","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":21, "ocr_count":24, "double_ocr_count":35}, #surf excel easy wash 1 ltr
        11: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":22, "ocr_count":28, "double_ocr_count":37}, #surf excel eash wash 500 ml 
        12: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":23, "ocr_count":24, "double_ocr_count":35}, #surf excel quick wash 1 ltr
        13: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":24, "ocr_count":28, "double_ocr_count":40}, #surf excel quick wash 500 ml
        14: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":7, "ocr_count":24, "double_ocr_count":35}, #surf_excel_matic_top_load_1_ltr
        15: {"ocr_light_tag":"LIGHT_SERAC2","ocr_camera_config":"path/to/config","ocr_tear_conf":0.10,"ocr_default_conf":0.05,"product_id":29, "ocr_count":24, "double_ocr_count":35}, #surf_excel_matic_front_load_1_ltr
    }

back_cam_configs = {
        1: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.4,"default_confidence":0.4,"product_id":2, "loose_cap_height":20, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort _blue_860_ml_morning fresh
        2: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.4,"default_confidence":0.4,"product_id":4, "loose_cap_height":20, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort pink 860 ml lily fresh
        3: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.4,"default_confidence":0.4,"product_id":32, "loose_cap_height":20, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort green 860 ml garden fresh
        4: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.55,"default_confidence":0.55,"product_id":3, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort black 860 ml desire 
        5: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.55,"default_confidence":0.55,"product_id":28, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort black 860 ml royale  
        6: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":30, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":4, "inner_cap":1}, #rin matic front load .
        7: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":25, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":4, "inner_cap":1}, #rin matic top load .
        8: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.7,"default_confidence":0.7,"product_id":31, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":6, "cap_class":1, "sleeve_class":1, "inner_cap":4}, #surf excel matic front load  ml500 .
        9: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.7,"default_confidence":0.7,"product_id":20, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":6, "cap_class":1, "sleeve_class":1, "inner_cap":4}, # surf execel matic top load 500 ml .
        10: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.3,"default_confidence":0.3,"product_id":21, "loose_cap_height":60, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel easy wash 1 ltr .
        11: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.7,"default_confidence":0.7,"product_id":22, "loose_cap_height":60, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel eash wash 500 ml .
        12: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.25,"default_confidence":0.25,"product_id":23, "loose_cap_height":35, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel quick wash 1 ltr .
        13: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.25,"default_confidence":0.25,"product_id":24, "loose_cap_height":35, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel quick wash 500 ml .
        14: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":7, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf_excel_matic_top_load_1_ltr .
        15: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":29, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf_excel_matic_front_load_1_ltr .
    }

front_cam_config = {
        1: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.35,"default_confidence":0.25,"product_id":2, "loose_cap_height":20, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort _blue_860_ml_morning fresh
        2: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.35,"default_confidence":0.25,"product_id":4, "loose_cap_height":20, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort pink 860 ml lily fresh
        3: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.35,"default_confidence":0.25,"product_id":32, "loose_cap_height":20, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort green 860 ml garden fresh
        4: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.55,"default_confidence":0.55,"product_id":3, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort black 860 ml desire 
        5: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.55,"default_confidence":0.55,"product_id":28, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":4, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #comfort black 860 ml royale  
        6: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":30, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":4, "inner_cap":1}, #rin matic front load .
        7: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":25, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":4, "inner_cap":1}, #rin matic top load .
        8: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.7,"default_confidence":0.7,"product_id":31, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":6, "cap_class":1, "sleeve_class":1, "inner_cap":4}, #surf excel matic front load  ml500 .
        9: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.7,"default_confidence":0.7,"product_id":20, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":6, "cap_class":1, "sleeve_class":1, "inner_cap":4}, # surf execel matic top load 500 ml .
        10: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.2,"default_confidence":0.2,"product_id":21, "loose_cap_height":60, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel easy wash 1 ltr .
        11: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.2,"default_confidence":0.45,"product_id":22, "loose_cap_height":60, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel eash wash 500 ml .
        12: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.45,"default_confidence":0.45,"product_id":23, "loose_cap_height":35, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel quick wash 1 ltr .
        13: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.45,"default_confidence":0.45,"product_id":24, "loose_cap_height":35, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf excel quick wash 500 ml .
        14: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":7, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf_excel_matic_top_load_1_ltr .
        15: {"model_weights":"path/to/model","camera_config":"path/to/config","tear_confidence":0.15,"default_confidence":0.15,"product_id":29, "loose_cap_height":45, "loose_cap_class":3, "dent_class":2, "tear_class":5, "cap_class":1, "sleeve_class":1, "inner_cap":1}, #surf_excel_matic_front_load_1_ltr .
    }

cld_cam_config={
        1: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":2,  "cld_count":16}, #comfort _blue_860_ml_morning fresh
        2: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":4,  "cld_count":16}, #comfort pink 860 ml lily fresh
        3: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":32,  "cld_count":16}, #comfort green 860 ml garden fresh
        4: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":3,  "cld_count":16}, #comfort black 860 ml desire 
        5: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":28,  "cld_count":16}, #comfort black 860 ml royale  
        6: {"camera_config":"path/to/config","default_confidence":0.45,"product_id":30,  "cld_count":12}, #rin matic front load .
        7: {"camera_config":"path/to/config","default_confidence":0.45,"product_id":25,  "cld_count":12}, #rin matic top load .
        8: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":31,  "cld_count":20}, #surf excel matic front load  ml500 .
        9: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":20,  "cld_count":20}, # surf execel matic top load 500 ml .
        10: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":21,  "cld_count":12}, #surf excel easy wash 1 ltr .
        11: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":22,  "cld_count":12}, #surf excel eash wash 500 ml .
        12: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":23,  "cld_count":16}, #surf excel quick wash 1 ltr .
        13: {"camera_config":"path/to/config","default_confidence":0.55,"product_id":24,  "cld_count":20}, #surf excel quick wash 500 ml .
        14: {"camera_config":"path/to/config","default_confidence":0.2,"product_id":7,  "cld_count":12}, #surf_excel_matic_top_load_1_ltr .
        15: {"camera_config":"path/to/config","default_confidence":0.2,"product_id":29,  "cld_count":12}, #surf_excel_matic_front_load_1_ltr .
    }

